### ISSUE TITLE
ember-filestack-picker is not a helper

### ISSUE THREAD

**Issue by miguelcobain** [mminkoff/ember-filestack#1]
When i write the following on my template

```hbs
{{ember-filestack-picker
  onSelection=(action "fileSelected")
  onClose=(action (mut showDialog) false)
  onError=(action "fileUploadError")}}
```

I get the following error:
```
ember.debug.js:26513 Error: Compile Error: ember-filestack-picker is not a helper
```

However, if I change to
```hbs
{{ember-filestack-picker/component
  onSelection=(action "fileSelected")
  onClose=(action (mut showDialog) false)
  onError=(action "fileUploadError")}}
```

it starts working normally.

I think this addon probably should not use pods when exporting the component in the `app` folder.
changing `app/components/ember-filestack-picker/component.js` to `app/components/ember-filestack-picker.js` might be enough.

**Comment by mminkoff** [comment]
@miguelcobain thanks for this.  I'm sorry not to have seen it sooner, and I'm glad you figured out a solution.  I've pushed a new version as you've described.  Please let me know if it solved the problem for you.
