### ISSUE TITLE
Does this ember addon support filestack security?

### ISSUE THREAD

**Issue by joshjeppson** [mminkoff/ember-filestack#12]
We use Filestack's security policy option: https://www.filestack.com/docs/concepts/security/
Is there a way to use this addon with that?

**Comment by mminkoff** [comment]
I might misunderstand but it seems that this is for calls directly to the API, likely from another server, not a browser, as it requires having the credentials in place and I don't see anything that is meant to generate them in the browser.  This seems consistent with security not being a part, from what I can tell, of [Filestack's JavaScript SDK](https://github.com/filestack/filestack-js).

**Comment by joshjeppson** [comment]
Works great in the browser. [Here](https://filestack.github.io/filestack-js/interfaces/clientoptions.html)'s the relevant documentation.

I've written a super thin and ugly wrapper around the filestack-js library. We call our own API to generate a security descriptor. We then initialize the picker code with code like this:
`let pick = Filestack.init(key, security).pick(options);`

I'd like to switch to using your library. Basically, I just need a way to pass options to the pick init method. Given your response, the answer to my original question is probably no. I'll see about putting together a PR to add it, if you don't mind.

**Comment by mminkoff** [comment]
I see - that's very helpful, thanks.  You should be able to do this by adding `clientOptions` to the `ember-filestack` hash in `config/environment.js`.

**Comment by mminkoff** [comment]
@joshjeppson any luck with the above?
