### ISSUE TITLE
How to access the file upload response?

### ISSUE THREAD

**Issue by rizkysyazuli** [mminkoff/ember-filestack#2]
Maybe i missed something important in the README. But how do I get the response data after a successful upload?

**Comment by mminkoff** [comment]
You're right - the README could use a more complete example.  A demo too.

Meanwhile, in the example template code you see that you can pass in an action for 'onSelection'.  That action will be called when a file is picked and it will be passed the data you need.

**Comment by rizkysyazuli** [comment]
@mminkoff yep2. it's not very obvious. but i figured that out in the end. thx man. super useful plugin.

just in case anyone's wondering. i got the uploaded image url like this:

```hbs
{{ember-filestack-picker options=fsOptions onSelection=(action "fsAction")}}
```

```js
actions: {
  fsAction(response) {
    this.set('model.logo', response.filesUploaded[0].url);
  }
}
```

**Comment by mminkoff** [comment]
I'd be happy to accept a pull request for the README... 😇

**Comment by rizkysyazuli** [comment]
@mminkoff ahaha. sure2. i'd be happy to. will do that in a bit.
